### ISSUE TITLE
Discussion: Alternative approach using normalized response

### ISSUE THREAD

**Issue by jonaskello** [gajus/graphql-deduplicator#19]
I developed a library to normalize/denormalize any graphql response which is available here: [graphql-norm](https://www.npmjs.com/package/graphql-norm). If you want a more compact response, I guess normalizing it before returning it and then denormalizing on the client could be an alternative too or does graphql-deduplicator do some more tricks to cut the size down?

**Comment by gajus** [comment]
No spam, please.
